export type StrategyLibraryEntry = {
  id: string;
  strategyId: string;
  name: string;
  family: string;
  badge: string;
  sourceLabel: string;
  sourceUrl: string;
  popularityNote: string;
  description: string;
  use: string;
  howItWorks: string;
  indicators: string[];
  entryRules: string[];
  exitRules: string[];
  riskRules: string[];
  assumptions: string[];
  defaults: { symbol: string; timeframe: "1day" | "1week" | "1month"; fast: number; slow: number };
};

/**
 * The single catalogue used by Research and the YouTube strategy page.
 *
 * Source links intentionally point to a YouTube community search rather than
 * claiming that one creator invented or endorses a rule. Performance numbers
 * are never stored here: the selected stock/date/cost inputs determine the
 * live backtest statistics shown after a run.
 */
export const STRATEGY_LIBRARY: StrategyLibraryEntry[] = [
  {
    id: "golden-cross",
    strategyId: "sma_crossover",
    name: "Golden Cross",
    family: "Trend following",
    badge: "Community favourite",
    sourceLabel: "YouTube community strategy family",
    sourceUrl: "https://www.youtube.com/results?search_query=golden+cross+trading+strategy",
    popularityNote: "Widely discussed long-term crossover",
    description: "A long-term SMA crossover for studying major trend changes.",
    use: "A slower signal that helps study extended market regimes.",
    howItWorks: "Buy when the 50-day SMA crosses above the 200-day SMA and exit on the reverse cross.",
    indicators: ["SMA 50", "SMA 200"],
    entryRules: ["Enter long on a 50 SMA cross above the 200 SMA."],
    exitRules: ["Exit on a 50 SMA cross below the 200 SMA."],
    riskRules: ["Long-only paper simulation with commission and slippage included."],
    assumptions: ["Signals are calculated after the close and filled on the next candle.", "A 200-candle warm-up is required before the first signal."],
    defaults: { symbol: "RELIANCE", timeframe: "1day", fast: 50, slow: 200 },
  },
  {
    id: "sma-crossover",
    strategyId: "sma_crossover",
    name: "20/50 SMA crossover",
    family: "Trend following",
    badge: "Core engine rule",
    sourceLabel: "YouTube community strategy family",
    sourceUrl: "https://www.youtube.com/results?search_query=20+50+sma+crossover+strategy",
    popularityNote: "Common beginner trend template",
    description: "A transparent moving-average crossover for medium-term trend research.",
    use: "A simple baseline for comparing stocks, timeframes, and costs.",
    howItWorks: "Buy when the 20-day SMA crosses above the 50-day SMA and exit on the reverse cross.",
    indicators: ["SMA 20", "SMA 50"],
    entryRules: ["Enter long when SMA 20 crosses above SMA 50."],
    exitRules: ["Exit when SMA 20 crosses below SMA 50."],
    riskRules: ["Review drawdown and losing streaks; no live order is placed."],
    assumptions: ["Signals use close T and fill at open T+1 to avoid look-ahead bias."],
    defaults: { symbol: "RELIANCE", timeframe: "1day", fast: 20, slow: 50 },
  },
  {
    id: "ema-crossover",
    strategyId: "ema_crossover",
    name: "20/50 EMA crossover",
    family: "Trend following",
    badge: "Frequently tested",
    sourceLabel: "YouTube community strategy family",
    sourceUrl: "https://www.youtube.com/results?search_query=20+50+ema+crossover+strategy",
    popularityNote: "Frequently used responsive trend setup",
    description: "A responsive medium-term trend signal with more weight on recent prices.",
    use: "Useful when comparing faster trend response against SMA rules.",
    howItWorks: "Buy when the 20-day EMA crosses above the 50-day EMA and exit on the reverse cross.",
    indicators: ["EMA 20", "EMA 50"],
    entryRules: ["Enter long when EMA 20 crosses above EMA 50."],
    exitRules: ["Exit when EMA 20 crosses below EMA 50."],
    riskRules: ["Costs are applied on every simulated entry and exit."],
    assumptions: ["Next-candle execution prevents look-ahead bias."],
    defaults: { symbol: "RELIANCE", timeframe: "1day", fast: 20, slow: 50 },
  },
  {
    id: "rsi-ema",
    strategyId: "rsi_ema",
    name: "RSI pullback + EMA filter",
    family: "Momentum / pullback",
    badge: "Popular momentum setup",
    sourceLabel: "YouTube community strategy family",
    sourceUrl: "https://www.youtube.com/results?search_query=rsi+ema+pullback+strategy",
    popularityNote: "Common RSI and trend-filter combination",
    description: "Looks for an oversold pullback while the broader EMA trend remains positive.",
    use: "Study whether pullbacks inside an uptrend have historically recovered.",
    howItWorks: "Buy below RSI 30 only when EMA 20 is above EMA 50; exit above RSI 70 or when the trend reverses.",
    indicators: ["RSI 14", "EMA 20", "EMA 50"],
    entryRules: ["Enter when RSI is below 30 and EMA 20 is above EMA 50."],
    exitRules: ["Exit when RSI is above 70 or EMA 20 falls below EMA 50."],
    riskRules: ["Stress-test RSI thresholds and review losing streaks."],
    assumptions: ["One long position is used with commission and slippage included."],
    defaults: { symbol: "RELIANCE", timeframe: "1day", fast: 20, slow: 50 },
  },
  {
    id: "rsi-mean-reversion",
    strategyId: "rsi_mean_reversion",
    name: "RSI mean reversion",
    family: "Mean reversion",
    badge: "Classic oscillator rule",
    sourceLabel: "YouTube community strategy family",
    sourceUrl: "https://www.youtube.com/results?search_query=rsi+mean+reversion+strategy",
    popularityNote: "Long-running oscillator study pattern",
    description: "Tests whether an oversold move tends to recover toward neutral momentum.",
    use: "Compare reversion behavior across volatile and ranging stocks.",
    howItWorks: "Buy when RSI is below 30 and exit when RSI returns above 50.",
    indicators: ["RSI 14"],
    entryRules: ["Enter when RSI falls below 30."],
    exitRules: ["Exit when RSI rises above 50."],
    riskRules: ["Mean reversion can fail during persistent downtrends."],
    assumptions: ["RSI thresholds are defaults and should be stress-tested."],
    defaults: { symbol: "TCS", timeframe: "1day", fast: 14, slow: 50 },
  },
  {
    id: "bollinger-reversion",
    strategyId: "bollinger_mean_reversion",
    name: "Bollinger Band reversion",
    family: "Mean reversion",
    badge: "Common retail setup",
    sourceLabel: "YouTube community strategy family",
    sourceUrl: "https://www.youtube.com/results?search_query=bollinger+bands+mean+reversion+strategy",
    popularityNote: "Common volatility-band study pattern",
    description: "Tests whether unusually weak closes revert toward a moving-average centre line.",
    use: "Explore volatility bands without treating a band touch as a guaranteed reversal.",
    howItWorks: "Buy below the lower Bollinger Band and exit when price returns above the middle band.",
    indicators: ["Bollinger Bands", "SMA 20"],
    entryRules: ["Enter when close falls below the lower Bollinger Band."],
    exitRules: ["Exit when close returns above the middle band."],
    riskRules: ["Review drawdown because bands can widen during persistent trends."],
    assumptions: ["Band width uses the engine's standard-deviation implementation."],
    defaults: { symbol: "TCS", timeframe: "1day", fast: 20, slow: 50 },
  },
  {
    id: "macd-crossover",
    strategyId: "macd_crossover",
    name: "MACD crossover",
    family: "Trend confirmation",
    badge: "Classic indicator",
    sourceLabel: "YouTube community strategy family",
    sourceUrl: "https://www.youtube.com/results?search_query=macd+crossover+strategy",
    popularityNote: "Classic momentum confirmation rule",
    description: "Uses a MACD line and signal-line cross to study momentum shifts.",
    use: "Compare momentum confirmation with moving-average-only rules.",
    howItWorks: "Buy when MACD crosses above its signal line and exit on the reverse cross.",
    indicators: ["MACD 12/26/9"],
    entryRules: ["Enter on a bullish MACD signal-line crossover."],
    exitRules: ["Exit on a bearish MACD signal-line crossover."],
    riskRules: ["This is a long-only historical simulation, not a recommendation."],
    assumptions: ["Standard MACD periods are used by the local engine."],
    defaults: { symbol: "INFY", timeframe: "1day", fast: 12, slow: 26 },
  },
  {
    id: "donchian-breakout",
    strategyId: "donchian_breakout",
    name: "Donchian breakout",
    family: "Breakout",
    badge: "Systematic trend setup",
    sourceLabel: "YouTube community strategy family",
    sourceUrl: "https://www.youtube.com/results?search_query=donchian+channel+breakout+strategy",
    popularityNote: "Widely discussed channel-breakout rule",
    description: "Tests whether a new rolling high can start a sustained move.",
    use: "Study breakout persistence and the cost of false breakouts.",
    howItWorks: "Buy above the previous rolling high and exit below the previous rolling low.",
    indicators: ["Donchian 50"],
    entryRules: ["Enter when close breaks above the prior rolling high."],
    exitRules: ["Exit when close breaks below the prior rolling low."],
    riskRules: ["Breakouts can create many small losses in sideways markets."],
    assumptions: ["Bands exclude the current candle to avoid look-ahead bias."],
    defaults: { symbol: "HDFCBANK", timeframe: "1day", fast: 20, slow: 50 },
  },
  {
    id: "momentum",
    strategyId: "momentum",
    name: "Price momentum",
    family: "Momentum",
    badge: "Simple persistence test",
    sourceLabel: "YouTube community strategy family",
    sourceUrl: "https://www.youtube.com/results?search_query=price+momentum+trading+strategy",
    popularityNote: "Simple lookback-return baseline",
    description: "Holds while the chosen lookback return is positive and exits when it turns negative.",
    use: "Create a simple baseline before testing more complex indicators.",
    howItWorks: "Buy when the lookback return is positive and exit when it turns negative.",
    indicators: ["Momentum 20"],
    entryRules: ["Enter when the selected lookback return is above zero."],
    exitRules: ["Exit when the selected lookback return falls below zero."],
    riskRules: ["Review sensitivity to lookback length and transaction costs."],
    assumptions: ["Signals execute on the next available candle."],
    defaults: { symbol: "HDFCBANK", timeframe: "1day", fast: 20, slow: 50 },
  },
  {
    id: "support-resistance-breakout",
    strategyId: "support_resistance_breakout",
    name: "Support / resistance breakout",
    family: "Price action",
    badge: "Video concept interpretation",
    sourceLabel: "Backtrack interpretation · review required",
    sourceUrl: "https://youtu.be/AYO62d__Bog",
    popularityNote: "Breakout above a prior trading range",
    description: "Buys a close above the previous range high and exits below the previous range low.",
    use: "Study whether a stock follows through after breaking a visible support/resistance range.",
    howItWorks: "The previous lookback high is resistance and the previous lookback low is support; signals use the current close and fill next candle.",
    indicators: ["Prior range high", "Prior range low"],
    entryRules: ["Enter long when the close breaks above the prior lookback high."],
    exitRules: ["Exit when the close breaks below the prior lookback low."],
    riskRules: ["Use the Strategy Lab stop-loss, take-profit, commission, and slippage controls."],
    assumptions: ["This is a configurable Backtrack interpretation, not a verbatim transcription of the video.", "Lookback defaults to 50 candles."],
    defaults: { symbol: "RELIANCE", timeframe: "1day", fast: 20, slow: 50 },
  },
  {
    id: "market-structure-break",
    strategyId: "market_structure_break",
    name: "Market-structure break",
    family: "Price action",
    badge: "Video concept interpretation",
    sourceLabel: "Backtrack interpretation · review required",
    sourceUrl: "https://youtu.be/AYO62d__Bog",
    popularityNote: "Range break with a trend filter",
    description: "Enters when price breaks a recent structure high while the fast trend remains above the slow trend.",
    use: "Test whether a higher-high structure break continues into a broader uptrend.",
    howItWorks: "A rolling prior high/low approximates market structure; an EMA filter avoids taking every range break.",
    indicators: ["Structure high/low", "EMA trend filter"],
    entryRules: ["Enter on a close above the prior structure high while fast EMA is above slow EMA."],
    exitRules: ["Exit below the prior structure low or when the EMA trend turns down."],
    riskRules: ["Treat the rolling structure as an approximation of swing points."],
    assumptions: ["This is a configurable Backtrack interpretation, not a verbatim transcription of the video.", "Fast/slow defaults are 20/50 candles."],
    defaults: { symbol: "HDFCBANK", timeframe: "1day", fast: 20, slow: 50 },
  },
  {
    id: "fibonacci-retracement",
    strategyId: "fibonacci_retracement",
    name: "Fibonacci retracement",
    family: "Price action",
    badge: "Video concept interpretation",
    sourceLabel: "Backtrack interpretation · review required",
    sourceUrl: "https://youtu.be/AYO62d__Bog",
    popularityNote: "Trend pullback near Fibonacci levels",
    description: "Buys an uptrend pullback that tests the 61.8% retracement and closes back above 50%.",
    use: "Study whether pullbacks within an uptrend recover toward the prior range high.",
    howItWorks: "Fibonacci levels are calculated from the previous rolling high and low; the high/low window excludes the current candle.",
    indicators: ["Fib 50%", "Fib 61.8%", "Fib 78.6%", "EMA trend filter"],
    entryRules: ["Enter when the fast EMA is above the slow EMA, the low reaches 61.8%, and the close recovers above 50%."],
    exitRules: ["Exit below 78.6% or above the prior rolling high."],
    riskRules: ["Fibonacci levels are calculated conventions, not guaranteed support."],
    assumptions: ["This is a configurable Backtrack interpretation, not a verbatim transcription of the video.", "The rolling range defaults to 50 candles."],
    defaults: { symbol: "RELIANCE", timeframe: "1day", fast: 20, slow: 50 },
  },
  {
    id: "price-action-reversal",
    strategyId: "price_action_reversal",
    name: "Price-action reversal",
    family: "Price action",
    badge: "Video concept interpretation",
    sourceLabel: "Backtrack interpretation · review required",
    sourceUrl: "https://youtu.be/AYO62d__Bog",
    popularityNote: "Bullish candle reversal in an uptrend",
    description: "Buys a bullish engulfing candle or hammer above the slow EMA and exits on bearish reversal or support loss.",
    use: "Test whether simple candle shapes add useful timing to a broader trend filter.",
    howItWorks: "Bullish engulfing and hammer-like candles are deterministic OHLC definitions; they are not discretionary chart reading.",
    indicators: ["Bullish engulfing", "Hammer", "EMA trend filter"],
    entryRules: ["Enter on a bullish engulfing or hammer candle while close is above the slow EMA."],
    exitRules: ["Exit on a bearish engulfing candle or a close below prior support."],
    riskRules: ["Candle-pattern definitions are simplified and should be reviewed on the chart."],
    assumptions: ["This is a configurable Backtrack interpretation, not a verbatim transcription of the video.", "The slow EMA defaults to 50 candles."],
    defaults: { symbol: "TCS", timeframe: "1day", fast: 20, slow: 50 },
  },
  {
    id: "supply-demand-zones",
    strategyId: "supply_demand_zones",
    name: "Supply / demand zones",
    family: "Price action",
    badge: "Video concept interpretation",
    sourceLabel: "Backtrack interpretation · review required",
    sourceUrl: "https://youtu.be/AYO62d__Bog",
    popularityNote: "Demand-zone reclaim setup",
    description: "Approximates a demand zone near a rolling low and buys when price reclaims the prior candle high.",
    use: "Study whether a low-area bullish reaction has continuation after the zone is reclaimed.",
    howItWorks: "A demand zone is represented by a bullish candle near the previous rolling low; supply is used as the failure/exit context.",
    indicators: ["Demand floor", "EMA trend"],
    entryRules: ["Enter when the prior candle is a bullish low-area demand candle and the current close breaks its high."],
    exitRules: ["Exit below the demand floor or when close falls below the fast EMA."],
    riskRules: ["Zone detection is a mechanical approximation of a discretionary supply/demand drawing."],
    assumptions: ["This is a configurable Backtrack interpretation, not a verbatim transcription of the video.", "The zone lookback defaults to 50 candles."],
    defaults: { symbol: "HDFCBANK", timeframe: "1day", fast: 20, slow: 50 },
  },
  {
    id: "ict-liquidity-fvg",
    strategyId: "ict_liquidity_fvg",
    name: "ICT-style liquidity sweep + FVG",
    family: "Price action",
    badge: "Simplified daily approximation",
    sourceLabel: "Backtrack interpretation · review required",
    sourceUrl: "https://youtu.be/AYO62d__Bog",
    popularityNote: "Liquidity sweep with fair-value-gap confirmation",
    description: "Buys when price sweeps a prior range low, closes back above it, and forms a bullish three-candle gap above a slow EMA.",
    use: "Explore an educational daily-bar approximation of liquidity and imbalance concepts.",
    howItWorks: "A sweep is a low below the prior structure low followed by a reclaim; an FVG is a current low above the high from two candles earlier.",
    indicators: ["Liquidity low", "Bullish FVG", "EMA trend filter"],
    entryRules: ["Enter when a prior structure low is swept and reclaimed with a bullish FVG while above the slow EMA."],
    exitRules: ["Exit below the structure low or when close falls below the fast EMA."],
    riskRules: ["This is not a full ICT implementation and daily candles cannot reproduce intraday detail."],
    assumptions: ["This is a configurable Backtrack interpretation, not a verbatim transcription of the video.", "Intraday liquidity behavior is not available in the official daily archive."],
    defaults: { symbol: "NIFTY 50", timeframe: "1day", fast: 20, slow: 50 },
  },
  {
    id: "multi-timeframe-trend",
    strategyId: "multi_timeframe_trend",
    name: "Multi-timeframe trend confirmation",
    family: "Price action",
    badge: "Video concept interpretation",
    sourceLabel: "Backtrack interpretation · review required",
    sourceUrl: "https://youtu.be/AYO62d__Bog",
    popularityNote: "Trend alignment across two timeframes",
    description: "Enters only when the selected timeframe and a higher timeframe both show an aligned EMA trend.",
    use: "Test whether higher-timeframe direction improves lower-timeframe trend signals.",
    howItWorks: "For daily tests the higher timeframe is weekly; for weekly tests it is monthly. Monthly tests use a quarterly proxy.",
    indicators: ["Current EMA trend", "Higher-timeframe EMA trend"],
    entryRules: ["Enter when current fast EMA is above current slow EMA and the higher-timeframe trend is also bullish."],
    exitRules: ["Exit when either timeframe loses its bullish EMA alignment."],
    riskRules: ["Higher-timeframe values are forward-filled only after completed higher-timeframe bars."],
    assumptions: ["This is a configurable Backtrack interpretation, not a verbatim transcription of the video.", "The higher timeframe is derived from saved NSE candles."],
    defaults: { symbol: "RELIANCE", timeframe: "1day", fast: 20, slow: 50 },
  },
];

export const STRATEGY_SOURCE_DISCLAIMER = "YouTube links are community search references, not endorsements. Popularity is not performance evidence; return, win rate, drawdown, and trade stats are calculated only after you choose the stock, dates, costs, and run a backtest.";
